spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql/product
    username: root
    password: root
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
