apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-app
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: builtImage
        type: image
  steps:
    - name: maven-build
      image: docker.io/maven:3.6-jdk-11-slim
      command:
        - mvn
      args:
        - clean
        - package
        - spring-boot:build-image
      env:
        - name: SPRING_CONTAINER_IMAGE_IMAGE
          value: fabricio211/product:1.58.0
      workingDir: "/workspace/source/"