#não usar, vamos usar o secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-product
data:
  application.yml: |-
                  spring:
                    application:
                      name: product
                    flyway:
                      locations:
                        - classpath:db/migration
                        - classpath:db/testdata
                    jpa:
                      show-sql: true
                    management:
                    endpoints:
                      web:
                        exposure:
                          include: "*"
                    metrics:
                      export:
                        prometheus:
                          enabled: true
                    endpoint:
                      metrics:
                        enabled: false
                      prometheus:
                        enabled: true
