apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: products
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "20"
        autoscaling.knative.dev/metric: "rps"
    spec:
      serviceAccountName: sa-products-svc
      containers:
        - image: fabricio211/product-service:4.2
          livenessProbe:
            httpGet:
              path: /actuator/info
          readinessProbe:
            httpGet:
              path: /actuator/health
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-server-credentials
            - name: SPRING_CONFIG_LOCATION
              value: file:/etc/config/application.yml
          envFrom:
            - secretRef:
                name: mysql-server-credentials
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 700Mi
              cpu: "300m"
            requests:
              memory: 700Mi
              cpu: "300m"
          volumeMounts:
            - mountPath: /etc/config
              name: config-products
      volumes:
        - name: config-products
          configMap:
            name: config-product
            items:
              - key: application.yml
                path: application.yml