spring:
  cloud:
    kubernetes:
      reload:
        enable: true
      secrets:
        name: mysql-server-credentials
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql/product
    username: root
    password: root
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true