spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://mysql:3306/product
    username: root
    password: root
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: springDemo
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: true