spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://database-1.chqfpdlyxbi9.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: megatron12
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true