apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: product-ingress
spec:
  rules:
    - host: api.estudo.kubernetes # Mude para o seu endereço
      http:
        paths:
        - backend:
            serviceName: products
            servicePort: 8080