apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc2
spec:
  selector:
    matchLabels:
      type: localmysql
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi # posso usar até 10GB do meu persistent volume que vamos vincular
